apiVersion: marketplace.kratix.io/v1
kind: ServiceNowRequest
metadata:
  name: postgres-servicenow
  namespace: default
spec:
  promise_name: postgresql
  description: "Provision PostgreSQL database for project X development environment"
  requested_by: "developer@company.com"
  priority: medium
  auto_approve: true
  resource_request:
    apiVersion: marketplace.kratix.io/v1alpha1
    kind: postgresql
    metadata:
      name: project-x-db
      namespace: default
    spec:
      size: small
      database: myapp