apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: dev-example
  namespace: default
spec:
  service:
    type: NodePort
    port: 8080
    nodePort: 30269
  configurationAsCode:
    configurations: []
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    disableCSRFProtection: false
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.479.2-jdk17
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 500Mi
        env:
          - name: DEBUG_JENKINS_OPERATOR
            value: "true"
          - name: JAVA_OPTS
            value: -Xmx2048m -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -Djenkins.install.runSetupWizard=false -Djava.awt.headless=true
    basePlugins:
      - name: kubernetes
        version: 4306.vc91e951ea_eb_d
      - name: workflow-job
        version: 1505.vea_4b_20a_4a_495
      - name: workflow-cps
        version: 4018.vf02e01888da_f
      - name: workflow-multibranch
        version: 800.v5f0a_a_660950e
      - name: workflow-aggregator
        version: 600.vb_57cdd26fdd7
      - name: git
        version: 5.7.0
      - name: git-client
        version: 6.1.1
      - name: job-dsl
        version: "1.90"
      - name: configuration-as-code
        version: 1932.v75cb_b_f1b_698d
      - name: kubernetes-credentials-provider
        version: 1.273.v15e69b_55ea_8e
      - name: pipeline-model-definition
        version: 2.2221.vc657003fb_d93
      - name: pipeline-model-extensions
        version: 2.2221.vc657003fb_d93
    plugins: []
