apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  name: postgresql
  labels:
    kratix.io/promise-version: v0.1.0
spec:
  destinationSelectors:
  - matchLabels:
      environment: dev
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: postgresql.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: postgresql
        plural: postgresql
        singular: postgresql
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    size:
                      default: small
                      description: |
                        Size of this PostgreSQL deployment. If small, it deploys PostgreSQL with 1Gi storage; if medium, 5Gi storage; if large, 10Gi storage with replica.
                      pattern: ^(small|medium|large)$
                      type: string
                    database:
                      default: "app"
                      description: |
                        Name of the initial database to create
                      type: string
                      minLength: 1
                      maxLength: 63
                  type: object
              type: object
          served: true
          storage: true
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-configure
          spec:
            imagePullSecrets:
            - name: ghcr-secret
            containers:
            - image: ghcr.io/prphub/kratix-state/postgresql-configure-pipeline:v0.1.4
              name: postgresql-configure-pipeline
    promise:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: promise-configure
          spec:
            imagePullSecrets:
            - name: ghcr-secret
            containers:
            - image: ghcr.io/prphub/kratix-state/postgresql-configure-pipeline:v0.1.4
              name: postgresql-configure-pipeline
status: {}