apiVersion: v1
kind: Secret
metadata:
  name: kratix-git-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: <your-git-repo-url>
  username: <your-git-username-base64>
  password: <your-git-password-base64>