apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-x-db
  namespace: project-x-dbspace
  labels:
    app: postgresql
    instance: project-x-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      instance: project-x-db
  template:
    metadata:
      labels:
        app: postgresql
        instance: project-x-db
    spec:
      containers:
      - name: postgresql
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: myapp
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: project-x-db-secret
              key: password
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: project-x-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: project-x-db-service
  namespace: project-x-dbspace
  labels:
    app: postgresql
    instance: project-x-db
spec:
  selector:
    app: postgresql
    instance: project-x-db
  ports:
  - port: 5432
    targetPort: 5432
    name: postgresql
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-x-db-pvc
  namespace: project-x-dbspace
  labels:
    app: postgresql
    instance: project-x-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: project-x-db-secret
  namespace: project-x-dbspace
  labels:
    app: postgresql
    instance: project-x-db
type: Opaque
data:
  password: cG9zdGdyZXMxMjM=  # postgres123
